---
- name: Safe Comet - Starting playbook saving comet in Vault
  ansible.builtin.debug:
    msg:  Safe Comet - Starting playbook saving comet in Vault on {{ inventory_hostname }}

- name: List of observed items
  ansible.builtin.debug:
    msg: "{{obj.key1 }}/{{ item }}"
  loop:
    - obj.key2